<a href="https://colab.research.google.com/github/fastestmk/Numpy-Basics/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])

print(a, type(a), a.shape)

[1 2 3] <class 'numpy.ndarray'> (3,)


In [ ]:
b = np.array([[1,2,3],[4,5,6]])

print(b)
print(b[0,0], b[0,1], b[1,2])

[[1 2 3]
 [4 5 6]]
1 2 6


Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((1,2)) # 1 row 2 columns
print(a)

[[0. 0.]]


In [ ]:
b = np.ones((1,3)) # 1 row 3 columns
print(b)

[[1. 1. 1.]]


In [ ]:
c = np.full((2,2), 5) 
print(c)

[[5 5]
 [5 5]]


In [ ]:
d = np.eye(3) # identity matrix
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
e = np.random.random((2,3))
print(e)

[[0.46885649 0.82249126 0.02365916]
 [0.50011573 0.61499959 0.48775385]]


#Indexing in numpy

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3] # slice first two elements of first row and 2 to 3 index of second row
print(b)

print(a[0,1])
b[0,0] = 77 # A slice of an array is a view into the same data, so modifying it will modify the original array.
print(a[0,1])
print(a)

[[2 3]
 [6 7]]
2
77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

row_r1 = a[0, :] # first row
row_r2 = a[1, :] # second row
row_r3 = a[1:2, :] # second row in 2-D matrix
row_r4 = a[[1], :] # second row in 2-D matrix
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)
print(row_r4, row_r4.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4] (4,)
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

col_r1 = a[:, 1] # second column
col_r2 = a[:, 1:2]
col_r3 = a[:, [1]]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)
print(col_r3, col_r3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
[[ 2]
 [ 6]
 [10]] (3, 1)


#Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0,1,2], [0,1,0]])
print(np.array([a[0,0], a[1,1], a[2,0]]))


[1 4 5]
[1 4 5]


# One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

b = [0, 2, 1, 2] # contains indexes

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b]) # refer to cell 39, 2nd line


# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  8 12]
[[11  2  3]
 [ 4  5 16]
 [ 7 18  9]
 [10 11 22]]


#Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_indx = (a > 2)
print(bool_indx)
print(a[bool_indx])
print(a[a>2]) # in one line

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


# Datatypes:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1,2], dtype=np.int64)  # Force a particular datatype
print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


# Array Math

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

print(np.sqrt(x))



[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


# Dot product or matrix multiplication

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v,w))
print(v@w)

print(x.dot(w)) # dot product of 2 by 2 matrix and 1 by 1 will 2 by 1
print(np.dot(x,w))
print(x@w)

print(x.dot(y))

219
219
219
[35 81]
[35 81]
[35 81]
[[19 22]
 [43 50]]


#Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum: 

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2,3],[3,4,5]])
z = np.array([[1,2,3],[3,4,5],[4,3,2]])
print(np.sum(x))
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

print(np.sum(y, axis=0))
print(np.sum(y, axis=1))

print(np.sum(z, axis=1))

#Transpose
print(x.T)
print(y.T)

10
[4 6]
[3 7]
[4 6 8]
[ 6 12]
[ 6 12  9]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]
 [3 5]]


Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

y = np.empty_like(x)

for i in range(4):
    y[i, :] = x[i, :] + v # add y array into each row of x

print(y)    


vv = np.tile(v, (4,1)) # Stack 4 copies of v on top of each other
print(vv)
y = x+vv
print(y)

#Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. 
#Consider this version, using broadcasting:
print(x+v)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


# Reshape matrices

In [ ]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5]) 

z = np.reshape(v, (3,1))*w
print(z)

[[ 4  5]
 [ 8 10]
 [12 15]]
